### ISSUE TITLE
Running on a directory fails with an error

### ISSUE THREAD

**Issue by furious-luke** [rudotriton/halstead-cli#2]
Hi there, this package seems to be broken at the moment. When running on a directory, for example with `halstead dir src`, I get the following error:

```
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

I'm running on Node v17.9.0.

**Comment by rudotriton** [comment]
I tried and it still works with 17.9 and 18.1, however, I'm not sure what causes this error in your case.

On the other hand, I don't think these metrics provide much value, if any. This project was initially put together for a demo and I should have archived it then. So you're better off finding something more meaningful than this.
